### ISSUE TITLE
Make Builds istructions

### ISSUE THREAD

**Issue by Danik2343** [leikareipa/pcbi-content#1]
Make Builds istructions
P.S I love 3d-frontends for emulators and e.t.c

**Comment by leikareipa** [comment]
The PCbi project has been in a bit of a disarray for a few years now.

I've found the source code a bit too messy and careless to keep public, and the binary builds went offline a while back as well due to changes in hosting. There wasn't a lot of interest in the project while it was available, so it's been low priority to sort out.

I'll think about it a bit and update you on the situation then.

**Comment by leikareipa** [comment]
The plan is to refactor the codebase a bunch and eventually make it open source. You'll find it here when it becomes available:  https://github.com/leikareipa/pcbi. The process will take some amount of time.
